# Languages configuration

en:
  languageCode: en-us
  title: Climate and Agriculture Research Group
  params:
    description: Research on climate-smart agriculture and food systems in Sierra Leone.
