[build]
  command = "hugo --gc --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.140.2"      # or match your local Hugo version
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
